import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import Sidebar from "@/components/Sidebar";
import { NotesProvider } from "@/context/useNotes";
import NextTopLoader from "nextjs-toploader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute={"class"} defaultTheme="system">
          <NotesProvider>
            <div className="flex min-h-screen bg-background text-foreground overflow-hidden">
              <NextTopLoader
                color="#2299DD"
                initialPosition={0.08}
                crawlSpeed={200}
                height={3}
                crawl={true}
                showSpinner={false}
                easing="ease"
                speed={200}
                shadow="0 0 10px #2299DD,0 0 5px #2299DD"
                zIndex={1600}
                showAtBottom={false}
              />
              <Sidebar />
              <main className="flex-1 flex flex-col items-start p-6 md:p-10 w-full relative overflow-y-auto max-h-screen">
                <div className="w-full max-w-6xl mx-auto flex flex-col gap-6">
                  {children}
                </div>
              </main>
            </div>
          </NotesProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
